### PR TITLE
Bug #7 - change info button:

### PR DESCRIPTION
**Pull request by marcioreisjr**
Hello Team,

I have added the description text related to each "relation" in their sections.

Also, I want to mention that I made minor modifications to the size of the help boxes to ensure they fit properly. However, I have left their original styling unchanged as I believe the remaining style may not be to my liking, but it is still appropriate.

Thank you.

### CODE REVIEW

**Review by jb-tlm — CHANGES_REQUESTED** [review]
It appears that bringing up this info box makes the bottom of the palette display disappear. Not sure if there is a weird setting for the overflow, but I would expect a scroll bar to appear that would allow the user to scroll down and see the hidden part of the palette display. 
It may not have anything wrong with the overflow. The palette display may not actually reach past the bottom of the screen triggering a scroll bar to pop up, the footer may have a high z value which hides the bottom of the palette display behind it. Whatever the cause, I think we should address this issue, it looks pretty bad when the new info comes up and the bottom of the palette display disappears with no way to scroll down.
image

**Comment by marcioreisjr** [comment]
Hi Jacob,

Interesting! I don't see this issue on my system. This is how it looks to me on the three major browsers when slightly constrained in horizontal and vertical sizes. Can you tell me the browser and platform you are using? This is the only computer I can access, but if you tell me what your platform and browser are, I can try inferring the issue.
Chrome Version 115 0 5790 114 (Official Build) (arm64)
Firefox 115 0 3 (64-bit) - MacBook Air M1
Safari - Version 16 6 (18615 3 12 11 2) - MacBook Air M1

**Comment by marcioreisjr** [comment]
Github has mangled the name of my files which contained the version of the browsers. Here they are:
- Chrome Version 115.0.5790.114 (Official Build) (arm64)
- Firefox 115.0.3 (64-bit) - MacBook Air M1
- Safari - Version 16.6 (18615.3.12.11.2) - MacBook Air M1

**Comment by marcioreisjr** [comment]
Please, verify the last commit.

Thanks,

**Pull request merged**
